spring:
  application:
    name: mmg-admin-service
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${ADMIN_DB_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

server:
  port: 8083

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

constants:
  jwt:
    issuer: ${JWT_ISSUER}
    bearer-format: JWT
    claim-key: signedUser
    secret-key: ${JWT_SECRET}
    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 1296000
    access-token-validity-milliseconds: ${JWT_ACCESS_TOKEN_VALIDITY_MS}
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/user/reissue
    refresh-token-cookie-validity-seconds: 1296000
    refresh-token-validity-milliseconds: ${JWT_REFRESH_TOKEN_VALIDITY_MS}
