spring:
  data:
    redis:
      host: redis-master.infra.svc.cluster.local
      port: 6379
      database: 0
logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.cache: TRACE
